# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Pavlov's Dad
motto: Nothing New Ever
email: wyseguys@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I am just squatting on this mediocre domain name and hogging up all the good email addresses for it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.wyseguys.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: wyseguys
github_username:  wyseguys
google_analytics: UA-639642-2


paginate: 5
paginate_path: "/blag/page:num/"


collections:
  shittyroommate:
    output: true
  wayne:
    output: true
  computer:
    output: true
  dictionary:
    output: true
  ashley:
    output: true
  inmypants:
    output: true
  zenjefe:
    output: true


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "MrChrister"
  -
    scope:
      path: ""
      type: "ashley" # previously `post` in Jekyll 2.2.
    values:
      layout: "ashley"
      collection-title: "The Secret-ish Blug"
      sitemap: false
  -
    scope:
      path: ""
      type: "shittyroommate"
    values:
      layout: "shitty"
      collection-title: "Shitty Roommate"
      attribution: "By Martin Random"
  -
    scope:
      path: ""
      type: "wayne"
    values:
      layout: "wayne"
  -
    scope:
      path: ""
      type: "computer"
    values:
      layout: "computer"
  -
    scope:
      path: ""
      type: "dictionary"
    values:
      layout: "dictionary"
  -
    scope:
      path: ""
      type: "zenjefe"
    values:
      layout: ""
      sitemap: false
  -
    scope:
      path: ""
      type: "inmypants"
    values:
      layout: "default"
      attribution: "From the mind of WCRTZJB"
      sitemap: false


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
